export default [
    {
        id:1,
        name:'Programming',
        icon:'/coding.jpeg',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/yoga.jpeg',
        prompt:''
    },
    {
        id:1,
        name:'Creative',
        icon:'/creative.jpeg',
        prompt:''
    }
]